// Generated by the lark-cli v0.8.  DO NOT EDIT!
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
package qian.xun.common.constant;


import qian.xun.common.constant.abstarct.EnumDisplayNameSupport;
import qian.xun.common.constant.abstarct.EnumValueSupport;
import qian.xun.common.constant.abstarct.Enums;

/**
 *
 */
public enum StatusEnum implements EnumValueSupport, EnumDisplayNameSupport {
    /**
     * 有效
     */
    NORMAL(1, "有效"),
    /**
     * 无效
     */
    INVALID(2, "无效");

    private int value;
    private String displayName;

    private StatusEnum(int value, String displayName) {
        this.value = value;
        this.displayName = displayName;
    }

    /**
     * 获取枚举的 int 值,用于数据保存以及序列化
     *
     * @return 枚举的 int 值
     */

    public int value() {
        return this.value;
    }

    /**
     * 获取枚举的显示名称
     *
     * @return 枚举的显示名称
     */

    public String displayName() {
        return this.displayName;
    }
    
    /**
     * 根据 int 值构建一个枚举对象
     *
     * @param value 需要构建枚举的 int 的值
     * @return 返回相应 value 值的枚举对象
     */
    public static StatusEnum valueOf(int value) {
        return Enums.valueOf(StatusEnum.class, value);
    }
}
