#LOGGING
logging:
    config: classpath:logback.xml
server:
    port: 8082
    compression:
        enabled: true
        mime-types: application/json,application/xml,text/html,text/xml,text/plain

multipart:
    enabled: true
    maxFileSize: 80Mb
    maxRequestSize: 100Mb
    location: ./upload
#spring config
spring:
    profiles:
        active: dev
    aop:
        auto: true
    h2:
        console:
            path: /h2-console #进入h2 web操作界面的路径
            enabled: true #开启h2 web界面
    datasource:
        driver-class-name: org.h2.Driver
        schema: classpath:db/schema-h2.sql
        url: jdbc:h2:file:d:/home/spring-boot-h2-db
        username: root
        password: test
# MyBatis
mybatis:
    mapper-locations: classpath*:qian/xun/dao/mybatis/user/*.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 在console打印sql语句